version: "3.7"
services:
  app:
    image: openjdk:11-jdk-slim  # Image Java OpenJDK 11
    command: sh -c "mvn clean package && java -jar target/your-app.jar"  # Compilation et exécution du JAR
    ports:
      - 8080:8080  # Port exposé pour l'application Java (assurez-vous que votre application écoute sur ce port)
    working_dir: /app
    volumes:
      - ./:/app  # Monter le répertoire local dans le container
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_DB: app_new_e_learning

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql  # Stockage des données MySQL
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: app_new_e_learning

volumes:
  todo-mysql-data:

